server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/RomperS/config-repository"
          search-paths:
            - '{application}'
            - '{application}/{profile}'

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${USERNAME}:${PASSWORD}@discovery-service:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      jvm: true
      process: true

logging:
  level:
    org.springframework.web: INFO
    com.example.configservice: DEBUG
