server:
  port: 8888

spring:
  application:
    name: config-service

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${USERNAME}:${PASSWORD}@localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      jvm: true
      process: true

logging:
  level:
    org.springframework.web: INFO
    com.example.configservice: DEBUG
